# cluster.name: "opensearch-cluster"
# node.name: "opensearch-node"
# discovery.type: single-node
# bootstrap.memory_lock: true

# Add analysis settings for synonyms
# index.analysis:
#   analyzer:
#     synonym_analyzer:
#       type: custom
#       tokenizer: standard
#       filter: ["lowercase", "synonym_filter"]
#   filter:
#     synonym_filter:
#       type: synonym
#       synonyms_path: synonyms.txt

# Add any additional custom configurations here 